### ISSUE TITLE
How this plugin works?

### ISSUE THREAD

**Issue by gurjyot** [pupi1985/q2a-random-avatar#1]
I placed some of my custom images in places of your images. Then uploaded the plugin and enabled it but nothing seems to work because the existing default avatar didn't changed for any of the users. Then I disabled default avatar in users section but that removed the avatars form all those users whom haven't uploaded their own avatars.
I am confused how it'll work for existing users who haven't uploaded any custom avatar?

**Comment by pupi1985** [comment]
In the home page I've explained this scenario:

> However, all users created before enabling Random Avatar who have never set an avatar in their profiles will be displayed the default avatar or none, if the Default avatar setting is disabled.
> If you read your question it covers exactly both situations.

If a user already exists then why would you change their avatar? The readme also states:

> Random Avatar is a Question2Answer plugin that assigns new users a random avatar
> So existing users are untouched.

This is equivalent to registering and then setting an avatar manually. After doing so, you no longer have a default avatar. The existing users who have not set their avatar are still caught by the default avatar rule.

**Comment by gurjyot** [comment]
Thanks for your time Gabriel. Sorry because I didn't read the Readme section. Now I know how the plugin works. :)
